### ISSUE TITLE
ARM Linux LibPcapLiveDeviceList.Instance Exception

### ISSUE THREAD

**Issue by TedXi** [dotpcap/sharppcap#553]
My runtime environment is ARM32 Linux version 5.4.61, and the system has the following library files:
```
SharpPcap 6.3.0 installed using nuget
./usr/lib/libpcap.so
./usr/lib/libpcap.so.1
./usr/lib/libpcap.so.1.9.0
```

My code only has one line as below：
`LibPcapLiveDeviceList devices = LibPcapLiveDeviceList.Instance;`

The problem is below：
```
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at SharpPcap.LibPcap.Sockaddr..ctor(IntPtr sockaddrPtr)
   at SharpPcap.LibPcap.PcapAddress..ctor(pcap_addr pcap_addr)
   at SharpPcap.LibPcap.PcapInterface..ctor(pcap_if pcapIf, NetworkInterface networkInterface, RemoteAuthentication credentials)
   at SharpPcap.LibPcap.PcapInterface.GetAllPcapInterfaces(IntPtr devicePtr, RemoteAuthentication credentials)
   at SharpPcap.LibPcap.PcapInterface.GetAllPcapInterfaces()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.GetDevices()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.Refresh()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList..ctor()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.get_Instance()
```

This code runs fine on x64 ubuntu and on x64 Windows.

What's going on? Is there anything I can do?

**Comment by kayoub5** [comment]
Stack trace similar to #518, could you try the fix from #534? it's already in master branch, but no release include it yet.

**Comment by TedXi** [comment]
> Stack trace similar to #518, could you try the fix from #534? it's already in master branch, but no release include it yet.
Thank you for your reply. I tried the latest code, and it works fine. According to the output, it seems that there are indeed some strange network interfaces on my system.
